using Microsoft.AspNetCore.Mvc;
using MoneyOrbit.Application.Helpers;
using MoneyOrbit.Application.Interfaces.IServices;
using MoneyOrbit.Application.DTOs.AiDtos;
using MoneyOrbit.Application.DTOs.GoalDtos;
using Google.Api.Gax.Grpc;

namespace MoneyOrbit.Infrastructure.Controllers
{
    public class AiController: BaseController
    {
        private readonly IAiService _aiService;
        private readonly ILogger<AiController> _logger;

        public AiController(IAiService aiService, ILogger<AiController> logger)
        {
            _aiService = aiService;
            _logger = logger;
        }

        [HttpGet("getAdvice")]
        public async Task<IActionResult> GetAdviceForGoal(GetGoalDto getGoalDto)
        {
            if (string.IsNullOrWhiteSpace(getGoalDto.GoalID))
            {
                return BadRequest("Goal ID cannot be empty.");
            }

            try
            {
                _logger.LogInformation("Request received for AI advice for Goal ID: {GoalId}", getGoalDto.GoalID);
                string advice = await _aiService.GetAdvice(getGoalDto);

                // You might want to wrap the advice in a structured response DTO
                return Ok(new AdviceResponse { Advice = advice });
            }
            catch (InvalidOperationException ex)
            {
                // Catch specific exceptions from your service (e.g., goal not found)
                _logger.LogWarning(ex, "Failed to get AI advice for Goal ID {GoalId}: {Message}", getGoalDto.GoalID, ex.Message);
                return NotFound(new { Message = ex.Message }); // Or BadRequest if it's a client error
            }
            catch (Exception ex)
            {
                // Catch any other unexpected errors
                _logger.LogError(ex, "An unexpected error occurred while getting AI advice for Goal ID: {GoalId}", getGoalDto.GoalID);
                return StatusCode(StatusCodes.Status500InternalServerError, "An internal server error occurred while generating financial advice.");
            }
        }

        [HttpGet("disclaimer")]
        public IActionResult GetDisclaimer()
        {
            return Ok(new { Disclaimer = "This advice is generated by an Artificial Intelligence and is for informational purposes only. It is not a substitute for professional financial advice from a certified planner. Always consult with a qualified financial professional before making any financial decisions." });
        }
    }
}
